mne-tools/mne-qt-browser

.github/workflows/qt_viz_tests.yml
.gitignore
MANIFEST.in
README.md
mne_qt_browser/conftest.py
mne_qt_browser/tests/test_speed.py
requirements_testing.txt
setup.cfg

1. Don't install `upstream/main` for now, use stable
2. Use `upstream/main` rather than `marsipu/pg_test`

FIX: Use upstream/main for tools

---

.github/workflows/qt_viz_tests.yml
mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_speed.py

Following https://github.com/mne-tools/mne-python/pull/9957 this should work

BUG: Make OpenGL opt-in

---

mne_qt_browser/_pg_figure.py

This fixes a bug where the data is not correctly showed when the parameter `start` is set to another value than `0`.

FIX: bug with parameter "start"

---

mne_qt_browser/_pg_figure.py

This shows the tooltip of the Overview-ComboBox immediately as suggested by @sappelhoff in #26.

FIX: Show Tooltip immediately

---

mne_qt_browser/__init__.py
mne_qt_browser/_pg_figure.py

When multiple plots of the same raw-object are started sequentially, probably a race condition between those threads accessing the same data prevent some threads from finishing.
Since only a single thread is used at startup of the plot to maintain interactivity, capping the `maxThreadCount` to 1 solves the problem (for multiple instances all Loading-Threads are queued and run sequentially).
When exiting the plot before the thread finished this could lead to unexpected hanging or even crashes. This PR also adds a cleanup for the threads when the application closes.
Fixes #19

FIX: Threading issues

---

mne_qt_browser/_version.py

I just installed mne-qt-browser at a specific commit **after** 0.1.6 (06e586a44fc7934b14ad7c0cde89f527bafbd879) to get an unreleased fix ... yet `mne sys_info` still showed me `0.1.6` as the version, which is a bit misleading.
I assumed you are following a "semver"-style of versioning for the proposed changes below.

[MAINT] bump `__version__` to dev

---

mne_qt_browser/_pg_figure.py

This PR adapts to the changes made in mne-tools/mne-python#10048 for the centralization of the Qt-Application intialization.
It should only be merged **after** the aforementioned PR is merged in the maintenance-branch of mne-python.

MNT: adapt to qtapp-centralization in mne-tools/mne-python#10048

---

mne_qt_browser/_pg_figure.py

This PR adds a wrapper for pyqtgraph's `mkColor` which makes PyQtGraphBrowser accept [all available matplotlib color-specifiers](https://matplotlib.org/stable/tutorials/colors/colors.html) (especially float-tuples with values from 0-1 where pyqtgraph would need values from 0-255)
Closes mne-tools/mne-python#10059

FIX: Accept all matplotlib color-specifiers

---

mne_qt_browser/_pg_figure.py

This fixes a minor bug where it was possible to drag annotation-regions at the lower or upper end of `raw.times` out of bounds.

FIX: Annotation-Regions cannot be moved out of bounds

---

.github/workflows/qt_viz_tests.yml

This PR avoids all CIs to fail for the branch `maint/0.24` from mne-python by setting `pytest==6.2.5`.
The cause is a `DeprecationError` which is fixed in mne-tools/mne-python#10120.

MNT: Downgrade pytest to pass tests with maint/0.24

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md

This adds the same PR-template as for mne-python (since the contribution guide applies for mne-qt-browser as well) and adds a CONTRIBUTING.md.

MNT: Add PR-Template and CONTRIBUTING.md

---

mne_qt_browser/_pg_figure.py

BUG: Fixes clicking into Channel-Axis for selecting bad channels

---

.github/workflows/release.yml

This adds an upload-workflow similar to [here](https://www.caktusgroup.com/blog/2021/02/11/automating-pypi-releases/).

add upload workflow

---

mne_qt_browser/_pg_figure.py

As in mne-tools/mne-python#10317, the parameter `bgcolor` has not been considered to set the background-color of the plot.
This is now fixed and fixes #50.

BUG: Set background-color with bgcolor

---

.github/workflows/qt_viz_tests.yml
mne_qt_browser/_pg_figure.py
mne_qt_browser/_version.py
mne_qt_browser/conftest.py
mne_qt_browser/tests/test_pg_specific.py
mne_qt_browser/tests/test_speed.py

This is work in progress for epochs support.
This PR depends on a [correspondent PR](https://github.com/mne-tools/mne-python/pull/10297) in mne-python.
<details>
<summary>Code I currently use for testing</summary>
```python
import mne
import os
import numpy as np
from mne.viz import use_browser_backend
sample_data_folder = mne.datasets.sample.data_path()
raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
'sample_audvis_raw.fif')
raw = mne.io.read_raw(raw_file)
events_path = os.path.join(sample_data_folder, 'MEG', 'sample',
'sample_audvis_raw-eve.fif')
events = mne.read_events(events_path)
onsets = np.arange(2, 8, 2) + raw.first_time
durations = np.repeat(1, len(onsets))
descriptions = ['Test1', 'Test2', 'Test3']
for onset, duration, description in zip(onsets, durations, …
```

ENH: Epochs support

---

.github/workflows/qt_viz_tests.yml
README.md
mne_qt_browser/_pg_figure.py
mne_qt_browser/conftest.py
mne_qt_browser/tests/test_speed.py
requirements_testing.txt

This implements support for plotting ICA with `ICA.plot_sources(raw)` and when #40 is merged also `ICA.plot_sources(epochs)`.
Depends on mne-tools/mne-python#10330
**REMINDER**: CI testing with the PR branch from mne-tools/mne-python#10330 has to be reverted before merging!

ENH: ICA support

---

mne_qt_browser/_pg_figure.py

This fixes the following minor bugs:

BUG: Fix offbound overview-drag

---

mne_qt_browser/_pg_figure.py

This gets rid of the unresolvable ref cycles for me so that this code works on #10359
```
SG_STAMP_STARTS=true PATTERN=15_inplace MNE_SKIP_INSTANCE_ASSERTIONS="Brain,Plotter,BackgroundPlotter,vtkPolyData,_Renderer" make html_dev-pattern
```

BUG: Disconnect the connect

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/figure.py

To fix https://github.com/mne-tools/mne-qt-browser/issues/77, we're going to want to publicly document what object from this package `add_figure` can operate on, and (same thing) what gets returned by `raw.plot`. Currently this would be `mne_qt_browser._pg_figure.PyQtGraphBrowser`. This PR changes it so that we can call it `mne_qt_browser.figure.MNEQtBrowser`, which is a bit verbose, but at least is clearly in a a public namespace and reflects how we now think about this browser (less about pyqtgraph, more about a native Qt browser that happens to use PyQtGraph for speed).

MAINT: Change name

---

mne_qt_browser/_pg_figure.py

The text alignment is still wrong for me but at least the text itself is now correct for Epochs…

Fix x axis label text for Epochs (it used to say Time)

---

mne_qt_browser/_pg_figure.py

Fixes #94
MWE:
```python
import mne
sample_dir = mne.datasets.sample.data_path()
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(sample_fname, preload=True)
raw.crop(tmax=60)
raw.plot(block=True, butterfly=True)
```
| before | after |
|----|---|
| <img width="1138" alt="Screen Shot 2022-04-05 at 20 10 10" src="https://user-images.githubusercontent.com/2046265/161821946-61d16f13-5d5b-476a-8789-ff40682cd432.png"> | <img width="1138" alt="Screen Shot 2022-04-05 at 20 09 56" src="https://user-images.githubusercontent.com/2046265/161821970-356e4aa8-5997-49d4-95ec-0606c94825e3.png"> |
cc @agramfort

Make MEG channel order in butterfly plot match order in overview bar

---

mne_qt_browser/_pg_figure.py

Also minor change for code health to enforce more explicit parameter specification when creation projection dialog window.
MWE:
```python
import mne
sample_dir = mne.datasets.sample.data_path()
sample_fname = sample_dir / 'MEG' / 'sample' / 'sample_audvis_raw.fif'
raw = mne.io.read_raw_fif(sample_fname, preload=True)
raw.crop(tmax=60)
raw.plot(block=True)
```
https://user-images.githubusercontent.com/2046265/161846060-dc4808b3-1f7c-45ee-969e-66d85657e6c9.mov

Always keep projectors window on top

---

.github/workflows/qt_viz_tests.yml

Looking at CIs I noticed that macOS takes ~5 minutes longer than the other CIs. It turns out this is also about how long it takes to run benchmarks on there. It seems a bit overkill to run them with every PR on every platform, so let's just disable them on macOS for now.

CI: Dont run benchmarks on macOS

---

mne_qt_browser/_pg_figure.py

Directly use the `devicePixelRatio` instead of the (incorrect) self-computation. On my system the old value was ~1.7 now it's the correct 2.
@hoechenberger feel free to review/merge if you're happy

BUG: Fix the pixel ratio

---

mne_qt_browser/_pg_figure.py

This at least sets up a framework by which we can set the dark mode analogs for our light-mode colors:
| main-dark | main/PR-light | PR-dark |
| -- | -- | -- |
| <img width="1000" alt="Screen Shot 2022-04-08 at 10 36 11 AM" src="https://user-images.githubusercontent.com/2365790/162459134-ea736ac0-2a86-4141-a06f-66b47e150f7b.png"> | <img width="1000" alt="Screen Shot 2022-04-08 at 10 39 02 AM" src="https://user-images.githubusercontent.com/2365790/162459741-b6e2916f-3cf3-4722-8ea9-ad6fe2c7b571.png"> | <img width="1000" alt="Screen Shot 2022-04-08 at 10 36 26 AM" src="https://user-images.githubusercontent.com/2365790/162459244-09d1a4ac-986f-43e1-a2e6-f513ffcc158e.png"> |
For now I tried to choose similar colors based on the matplotlib list.
@mscheltienne you mentioned the colors not being …

ENH: Better dark colors

---

requirements.txt
setup.py

`darkdetect` and `qdarkstyle` are 2 optional dependencies for theme management.
I think they are used by `mne-python` before invoking the browser, but since theme selection is a key feature of the browser, how about adding them as a requirement here as well? This way, a base install of `mne` will include them by default. 
If they are used by other GUI through `mne-python`, then maybe it would be worth adding them to one of the `requirements_extra.txt` of `mne-python` as well.

Add theme related req to requirements.txt

---

.github/workflows/qt_viz_tests.yml
mne_qt_browser/_pg_figure.py

1. Check `self.mne.overview_mode` for validity
2. Support MNE_BROWSER_OVERVIEW_MODE in MNE-Python (https://github.com/mne-tools/mne-python/pull/10501)
3. Ensure the splash screen is always closed, including when there is an error in `__init__`
4. Remove `self.mne.show_overview_bar` in favor of just using `self.mne.overview_bar.isVisible()` (let Qt keep track instead of us)

ENH: Allow passing overview_mode

---

mne_qt_browser/_version.py

I think we should cut a release. Given that this will be the first to support Qt6, I bumped to 0.3.0 (last release was 0.2.6).
@agramfort or @hoechenberger feel free to merge and I'll cut a release

MAINT: Bump version for release

---

.coveragerc
mne_qt_browser/_fixes.py
mne_qt_browser/_pg_figure.py

1. Allow `_qt_raise_window` to actually control window-raising behavior
2. If you click away from mne-qt-browser, then back to it using a child dialog, the main window should be raised. This can be tested locally with:
```
import mne
raw = mne.io.read_raw_fif(mne.datasets.sample.data_path() / 'MEG' / 'sample' / 'sample_audvis_raw.fif')
raw.plot(group_by='selection', block=True)
```
3. Move backported functionality to `mne_qt_browser/_fixes.py`
4. No need to `self.mne.splash.close()` in `show` as this will be handled already by `_safe_splash`

ENH: Respect activation

---

mne_qt_browser/_pg_figure.py

Fixes #74.
This closes annotations-mode when pressing escape.

[BUG]: Close annotations-mode when pressing escape

---

mne_qt_browser/_pg_figure.py

Fixes #75 .
This fixes the browser not respecting event-id passed into `raw.plot()`.

[BUG]: Correctly label events according to the event_id dictionary if provided

---

mne_qt_browser/_pg_figure.py

The following seems to return `None` in some cases and result into an error that prevents the browser from starting.
`screen = QGuiApplication.screenAt(widget.mapToGlobal(QPoint(widget.width() // 2, 0)))`

BUG: Screen not fetched

---

.github/workflows/qt_viz_tests.yml

This fixes failing maintenance-CIs for backwards-compatitibility. With mne<1.1, the CIs on `ubuntu-latest` fail, because a fix from mne-tools/mne-python#10923 hadn't been implemented then.

BUG: Always newest xvfb-fix from mne

---

mne_qt_browser/_pg_figure.py

Fixes #82
This fixes an issue where in an interactive python console some Qt-Objects had been deleted if they hadn't been added to the Scene.
Before on every change of X-Range, Qt-Objects for Annotations and Events had been added and removed according to if they appear in this X-Range or not. In early testing this had been proven to be more performant with large sets of Annotations/Events.
This PR removes that and always adds all Qt-Objects for Annotations and Events to the Scene where Qt handles everything then.
With reasonable amounts of Annotations/Events (probably most common usecase) this new solutionis probably as good if not even better.
IMHO running the browser in an interactive python console without issue outweighs a potential benefit the former method had in some rarer cases.

remove add/remove objects for view-range

---

mne_qt_browser/_pg_figure.py

(Temporarily) fixes #137
This fixes a bug where the mouse movement is picked up from the overview-bar and the channel-selection-picker (`group_by='selection'`) always when the mouse is moved above and not only when a mouse-button is pressed.
This bug only seems to appear on Windows when pyqt>=5.15.4 is installed with conda. Since we didn't find a suitable fix yet, this PR disables dragging on the overviewbar on Windows until a better solution is found.

BUG: (temporarily) fix MouseMove-Bug on windows

---

.github/workflows/qt_viz_tests.yml
mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py
mne_qt_browser/tests/test_speed.py
requirements_testing.txt

In https://github.com/mne-tools/mne-python/pull/11205 you can see reference problems pop up on CircleCI, GH Actions, and Azure when we assert that garbage can be collected properly on plotter close. This is because PyQt5/PyQt6 appear to have issues when `signal.connect` is called using a `partial` of a bound method -- `gc` can't seem to resolve these on its own. I think we can fix them using `weakref.WeakMethod`, which I've done here.
Also becomes more selective about error resolution by only allowing disconnect errors when it's a separator (i.e., `action.text() == ''`, since `addSeparator` actually creates a `QAction` in the toolbar).
To verify this is the correct fix, though, we should try using this branch in https://github.com/mne-tools/mne-python/pull/11205 and make sure CIs come …

BUG: Fix ref bug using weakref

---

mne_qt_browser/_pg_figure.py

Fixes #167, `mne.global_data` was not correctly pre-computed because of an indexing error. 
~~It looks to me like `main._rerun_precompute()` must be run before updating the xRange, to run through https://github.com/mne-tools/mne-python/blob/d158117a716512fbe96d8ff6c4d735f1e9601d09/mne/viz/_figure.py#L349-L385 and to apply the visualization filters.~~
--------------
~~For the click on the overview bar, I'm lacking a good idea to fix it. The update happens in the OverviewBar class, here: https://github.com/mne-tools/mne-qt-browser/blob/f07ab8a2509b6d76c1fca9d2a2326c545a25eb1c/mne_qt_browser/_pg_figure.py#L1050~~
~~and it doesn't have a reference to `main`, to `_rerun_precompute` or to `load_thread`..~~
--------------
~~There is also this update in the `TimeScrollBar` class: …

Fix scrolling through data with a visualization filter

---

mne_qt_browser/_pg_figure.py

I found that the left/right arrow keys were scrolling by 3-4x the current `duration` when they should have scrolled by 1/4 of `duration`. This was because `scroll_sensitivity` was being included when a keypress was used. This fixes it.

BUG: Fix bug with arrow-key-based scrolling

---

mne_qt_browser/_pg_figure.py

So, pressing "h" on a `Raw` would not do anything, until you close the browser and open it again. Nice traceback ;)
The key `h` calls `_toggle_epoch_histogram`, which is not checking if we are plotting raw or epochs; while the function `_toggle_epoch_histogramm` with 2 `m` at the end does the same stuff correctly and is unused. 
This PR fixes that typo and removes the shortcut `h` entirely for raw recordings.

Remove shortcut "h" plotting epoch PTP amp when viewing raw

---

mne_qt_browser/_pg_figure.py

Don't allow "T" shortcut if we don't have a measurement date.
Traceback:
```
TypeError                                 Traceback (most recent call last)
File ~\pyvenv\mscheltienne\eeg-flow\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py:654, in AxisItem.paint(self, p, opt, widget)
652 if self.style["tickFont"]:
653     painter.setFont(self.style["tickFont"])
--> 654 specs = self.generateDrawSpecs(painter)
655 profiler('generate specs')
656 if specs is not None:
File ~\pyvenv\mscheltienne\eeg-flow\lib\site-packages\pyqtgraph\graphicsItems\AxisItem.py:1100, in AxisItem.generateDrawSpecs(self, p)
1098 if tickStrings is None:
1099     spacing, values = tickLevels[i]
-> 1100     strings = self.tickStrings(values, self.autoSIPrefixScale * self.scale, spacing)
1101 else:
1102     strings = …
```

Disable time format if we don't have a measurement date

---

mne_qt_browser/_pg_figure.py

Reported [here](https://mne.discourse.group/t/eyetracking-and-qt-browser-traces-of-x-y-position-disappear/7254/3) by @sappelhoff 
cc @scott-huberty

Fix removal of DC on precomputed data when nan's are present in the array

---

.github/workflows/qt_viz_tests.yml
.pre-commit-config.yaml
mne_qt_browser/_pg_figure.py
mne_qt_browser/conftest.py

1. Push windows to the back by default (helps when running `pytest` from the terminal not to see a million windows pop up)
2. Use `pre-commit.ci` to take care of style
3. Test prerelease NumPy and matplotlib (see also https://github.com/mne-tools/mne-python/pull/11837)

MAINT: Use pre-commit and updates for NumPy

---

mne_qt_browser/_pg_figure.py

This changes the width of the vline to improve visibility as suggested in #155.
It also adds that the vline-label changes color too when the mouse hovers over the vline.
@larsoner @mscheltienne WDYT should be the width (examples in #155)?

ENH: Improve vline

---

mne_qt_browser/_pg_figure.py

This fixes an error when hitting "Remove description" when all are already removed
```python
import mne
import os
import numpy as np
from mne.viz import use_browser_backend
sample_data_folder = mne.datasets.sample.data_path()
raw_file = os.path.join(sample_data_folder, 'MEG', 'sample',
'sample_audvis_raw.fif')
raw = mne.io.read_raw(raw_file)
annotations = mne.Annotations([1, 10, 20, 30],
[1, 2, 1, 2],
['a', 'b', 'a', 'b'])
raw.set_annotations(annotations)
with use_browser_backend('qt'):
browser = raw.plot(events=events, block=True, title='Sample-Data',
clipping=None, show=True, precompute=True,
use_opengl=True, theme='auto')
```
Then remove all descriptions from the plot in annotation mode and hit "Remove description" again.

Fix: remove description bug

---

mne_qt_browser/_pg_figure.py

Closes #186
The projectors were updated, but the update was not applied. Likely the pre-computation has to be re-run.
Anyway, that small change fixes the issue. It does however mean that we run twice through `self._update_projector()` because `_toggle_bad_channel` defined in `mne-python` runs it as well, but the cost is small.
Also, I noticed an import of the Qt5 backend at the top of the file. I'm guessing that whatever functionality uses it is currently failing with a Qt6 binding, but I did not test this. We had a similar import in `mne-icalabel` that failed when we started using 22.04 LTS + `qt6-base-dev` instead of 20.04 LTS + `qt5-default` (https://github.com/mne-tools/mne-icalabel/pull/120).

Apply the update to the projectors on bad channel toggle

---

mne_qt_browser/_pg_figure.py

In https://github.com/mne-tools/mne-python/pull/11903 we're trying to make some mne/io stuff private. This changes mne-qt-browser to use the explicitly public API (with two exceptions that we won't port over for now)

MAINT: Use public API

---

mne_qt_browser/_pg_figure.py

Every once in a while in testing I get:
```
________________________________________________________________________ test_plot_instance_components[qt] _________________________________________________________________________
mne/viz/tests/test_ica.py:521: in test_plot_instance_components
fig._fake_click((x, y), xform="data")
../mne-qt-browser/mne_qt_browser/_pg_figure.py:4665: in _fake_click
raise RuntimeError(f'There as been an {exc[0]} inside the Qt '
E   RuntimeError: There as been an <class 'RuntimeWarning'> inside the Qt event loop (look above for traceback).
...
Traceback (most recent call last):
File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 378, in sendClickEvent
item.mouseClickEvent(ev)
File …
```

MAINT: Safer check

---

.gitignore
mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

Make the tooltips more helpful, don't simply repeat what is visible on the buttons themselves.

Improve toolbar tooltips

---

mne_qt_browser/_pg_figure.py

Related to #199, this PR checks before the first qtpy import if the `QtBindingsNotFoundError` exception is thrown. The error message now hints that pyqt5 needs to be installed.

Improve error message if qt binding could not be found

---

mne_qt_browser/_pg_figure.py

Fix for https://app.circleci.com/pipelines/github/mne-tools/mne-python/21813/workflows/d8396d6c-3548-4ea5-919c-35835d7fcbdf/jobs/61343 / `epochs.get_data(..., copy=None)` deprecation

MAINT: Update for new copy kwarg

---

.gitignore
CONTRIBUTING.md
MANIFEST.in
pyproject.toml

To fix editable installs. We already switched over MNE-Python, MNE-BIDS, and MNE-BIDS-Pipeline.

Use hatchling as build backend

---

mne_qt_browser/_fixes.py
mne_qt_browser/_pg_figure.py

Setting the app name in the macOS menu bar is an ugly hack I just realized. The issue is that it overwrites any previously set name, so once again, starting MNE-Qt-Browser from MNELAB changes the name from "MNELAB" to "MNE-Python".
Since (1) this is a hack and (2) it is not really necessary to change the name for MNE-Qt-Browser (the default is "Python"), I would like to remove it.

Remove fixes for MNE < 1.0

---

pyproject.toml

https://github.com/conda-forge/mne-qt-browser-feedstock/pull/29 pointed out we don't use `packaging` anymore so let's get rid of it in `pyproject.toml`

MAINT: Remove packaging as dependency

---

pyproject.toml

Sorry for not creating an issue first, I was a bit lazy and I was hoping this would be okay since there is no change to the actual code.
I noticed that the project urls "homepage" and "repository" were pointing to mne-bids-pipeline and not mne-qt-browser (these links appear for example on the PyPi release page). 
I fixed the repository url, but don't think there is a homepage, right? An option might be to just remove the homepage url if there isn't any. I made it also point to the GitHub repo for the moment.
Additionally I changed "changelog" to an https not http url.

Fix project urls in pyproject.toml

---

mne_qt_browser/_pg_figure.py

Thanks for contributing a pull request! Please make sure you have read the
[contribution guidelines](https://mne.tools/dev/install/contributing.html)
before submitting.
Please be aware that we are a loose team of volunteers so patience is
necessary. Assistance handling other issues is very welcome. We value all user
contributions, no matter how minor they are. If we are slow to review, either
the pull request needs some benchmarking, tinkering, convincing, etc. or more
likely the reviewers are simply busy. In either case, we ask for your
understanding during the review process.
Again, thanks for contributing!
https://github.com/mne-tools/mne-qt-browser/pull/230 , https://github.com/mne-tools/mne-python/issues/10888 , https://github.com/mne-tools/mne-qt-browser/pull/212
Adds to the …

Enh ch type scale display

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

https://github.com/mne-tools/mne-qt-browser/pull/230 , https://github.com/mne-tools/mne-python/issues/10888 , https://github.com/mne-tools/mne-qt-browser/pull/212
Spinboxes in channel scalings within Settings can now be updated
This is the second of 4 or 5 PRs to allow display and scaling of channel types based on sensor units and monitor resolution and size

channel scaling spinboxes update

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

https://github.com/mne-tools/mne-qt-browser/pull/230 , https://github.com/mne-tools/mne-qt-browser/pull/212 , https://github.com/mne-tools/mne-qt-browser/pull/208 , https://github.com/mne-tools/mne-python/issues/10888
Adds widget to settings dialog displaying units of sensor in relation to screen size. Ability to edit widgets will be done in future pull request

Enh: channel sensitivity ui

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

[Example: Fixes #1234.](https://github.com/mne-tools/mne-qt-browser/issues/267)
Fix issues when combining channel-based annotations with another annotation.
Channel-based annotation can not merge with any other annotation.

Bug channel annot merge

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

https://github.com/mne-tools/mne-qt-browser/pull/230 , https://github.com/mne-tools/mne-qt-browser/pull/212 , https://github.com/mne-tools/mne-qt-browser/pull/208 , https://github.com/mne-tools/mne-python/issues/10888 , https://github.com/mne-tools/mne-qt-browser/pull/273
Extends  https://github.com/mne-tools/mne-qt-browser/pull/273 by enabling sensitivity spinboxes to be updated

Enh sensitivity UI change

---

mne_qt_browser/_pg_figure.py

In finding #270 I noticed that just opening the Settings dialog triggered 3 updates. There is no reason this is necessary, and is an unnecessary slowdown. It happens because we connect the listener then set the value (to it's currently used value)... which triggers an update.
And this is a bug for `antialiasing` actually because it triggers an AA toggle, so if you had AA on, it connected the listener, set the `setChecked(True)` which initiated a toggle, *disabling* AA. So the check state was always out of phase with the actual state.

BUG: Fix bug with over-updating and antialias toggle

---

.github/workflows/qt_viz_tests.yml
mne_qt_browser/_pg_figure.py

Get rid of this unhelpful warning:
```
/home/larsoner/python/mne-qt-browser/mne_qt_browser/_pg_figure.py:3575: RuntimeWarning: Failed to disconnect (None) from signal "triggered()".
sig.disconnect()
```
And also test against latest dev branch of pyqtgraph.

ENH: Swallow PySide6 warning

---

mne_qt_browser/_pg_figure.py

Zen mode should also hide the status bar

ENH: Hide status bar in zen mode, too

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

Fixes issue #12893 in mne-python (https://github.com/mne-tools/mne-python/issues/12893)
The issue is also discussed in PR #12895 in mne-python (https://github.com/mne-tools/mne-python/pull/12895)
Currently, when annotating bad epochs in mne-qt-browser, annotations were limited to the last sample of the recording, so that the last sample of the recording would not actually be rejected.
This fixes this issue, and additionally allows for 1-sample annotations at the start (t=0) and end (t=xmax) of the recording.
- raise upper limit of RawViewBox to xmax + 1 sample, so that new annotations can extend above the recording
- raise upper limit of AnnotRegion to xmax + 1 sample for all annotations
- to allow for 1-sample annotations at the beginning (0) and end (xmax) of recording in the …

Fix annotation of last sample

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

This allows the extra-data-loading gymnastics in https://github.com/mne-tools/mne-python/pull/13183. Also adds a little test that the downsampling stuff actually works (I wasn't sure looking at the code at first).

ENH: Make _process_data arg/kwarg agnostic

---

mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py

Closes #316
closes #321 (supersedes)
Fixes https://app.circleci.com/pipelines/github/mne-tools/mne-python/27161/workflows/2911c6d2-73fa-46e0-beda-08809c3d38c0/jobs/72600?invite=true#step-143-13979_105

BUG: Fix bug with single channel annot ypos
