mne-tools/mne-qt-browser

.github/workflows/qt_viz_tests.yml
codecov.yml
requirements.txt
requirements_testing.txt
setup.cfg
setup.py

Let's see how close I got
Closes #2

MRG, CI: Restore CIs

---

README.md

This PR adds troubleshooting and improves instructions in README.md

DOC: Improve README.md

---

mne_qt_browser/_pg_figure.py

This PR improves the Help-Dialog of the browser which now looks like this:

ENH: Improves the Help-Dialog

---

README.md
mne_qt_browser/_pg_figure.py
mne_qt_browser/conftest.py
mne_qt_browser/tests/test_speed.py

This fixes minor issues with CIs and tests.

MNT: Fix minor CI/Test-issues

---

mne_qt_browser/_pg_figure.py

This implements changes related to mne-tools/mne-python#9960.

MNT: Adaptions related to mne-tools/mne-python#9960

---

mne_qt_browser/_pg_figure.py

This adds some features wished for in #27:
- Overview-Mode "empty" with no background
Bugs fixed:
- Annotation-Colors not updating in overviewbar when changed

ENH: "empty"-mode for overview-bar, some fixes

---

mne_qt_browser/_pg_figure.py

Sorry, used the wrong key @marsipu :( BROWSER not BROWSE...
Probably worth another point release for this one

FIX: Fix key

---

mne_qt_browser/_pg_figure.py

Companion of https://github.com/mne-tools/mne-python/pull/10412
https://user-images.githubusercontent.com/2365790/156797553-1d9a8fab-a9cc-491f-b8f1-d9ca44eea823.mp4

ENH: Add splash

---

.gitignore
mne_qt_browser/_pg_figure.py

FIX: Darkness

---

mne_qt_browser/_pg_figure.py

We should use logical pixels for line widths. My display has a physical-to-logical ratio of 1.777. The difference is subtle but it's there.
Before:
After:

ENH: Better HiDPI support

---

mne_qt_browser/_pg_figure.py

Fixes shift-arrow behavior for me on macOS. Also it will fix the bug with https://github.com/mne-tools/mne-qt-browser/pull/104
I'm going to go double-check that this works on Windows and Linux.

BUG: Modifiers

---

mne_qt_browser/_version.py

Bumping to 0.4.dev0 now that 0.3.0 is out

MAINT: Bump version

---

mne_qt_browser/_pg_figure.py

This fixes a small bug, where the time/horizontal scroll-bar is not updated correctly after a chang in scroll_sensitivity.

BUG: Fix horizontal scrollbar updating wrong for scroll_sensitivty change

---

mne_qt_browser/_pg_figure.py

This fixes a small bug when using the crosshair (activated by pressing `x`).

BUG: Fix crosshair

---

.github/workflows/qt_viz_tests.yml
README.md
mne_qt_browser/_pg_figure.py
mne_qt_browser/conftest.py
mne_qt_browser/tests/test_speed.py
requirements.txt
requirements_testing.txt

Unclear why https://github.com/mne-tools/mne-qt-browser/pull/157 isn't running tests, but our most recent CI run (a month ago!) failed, so let's try this.

MAINT: Fix CIs

---

mne_qt_browser/_pg_figure.py

Closes #156 
Closes #159 
The channel selection is the same issue but is more difficult to fix since the method is called either directly or through `_methpartial`, and the lasso misbehavior is likely a different issue..

Fix bug with _overview_radio_clicked and channel selection with group_by='position'

---

.github/workflows/qt_viz_tests.yml
mne_qt_browser/_pg_figure.py

@mscheltienne can you see if being on this branch and https://github.com/mne-tools/mne-python/pull/11614 helps your use case at all? For me 3000 annotations is pretty usable but 10000 gets pretty slow still.
Closes #161

ENH: Speed up

---

.github/workflows/mne_1_4.patch
.github/workflows/qt_viz_tests.yml

Hopefully green then merge the 0.5.2 release

MAINT: Patch old MNE ver test

---

mne_qt_browser/_pg_figure.py

@marsipu Following #181, that's what was causing the weird hovering behavior on my side.

Add missing update of the label of a VLine

---

mne_qt_browser/_pg_figure.py

This improves the settings dialog by:

Improve settings dialog

---

.git_archival.txt
.gitattributes
.github/workflows/qt_viz_tests.yml
README.md
mne_qt_browser/__init__.py

This changes the version-system and adds update-instructions according to mne-tools/mne-python#12245

Remove version file

---

mne_qt_browser/_pg_figure.py

Just some minor cruft I found while looking through the code in #241

MAINT: Remove cruft

---

.git_archival.txt

Remove ref-names from .git_archival.txt

---

mne_qt_browser/_colors.py
mne_qt_browser/_pg_figure.py
mne_qt_browser/tests/test_pg_specific.py
pyproject.toml

Closes #256
Closes https://github.com/mne-tools/mne-python/issues/12653
@hoechenberger feel free to merge if you're happy

MAINT: Remove colorspacious dependency

---

.github/pull_request_template.md

In https://github.com/mne-tools/mne-qt-browser/pull/263 I noticed that a bunch of unnecessary text shows up, so in case people don't delete it on their own let's put it in a HTML comment.

MAINT: Update PR template

---

.github/workflows/qt_viz_tests.yml

I noticed that `codecov` wasn't commenting on PRs. Let's see if this fixes it 🤞

MAINT: Fix Codecov

---

pyproject.toml
tests/conftest.py

This makes it possible to run the entire test suite without having to clone and `pip install -e` the MNE-Python repo.

Add local test_raw.fif
